import os
import json
import time
from datetime import datetime, timezone
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

load_dotenv()

LLM_MODEL = "gpt-4o-mini"

# ── Why a dedicated compliance summariser? ─────────────────
# The risk extractor outputs structured risk indicators.
# The compliance summariser does something different —
# it generates an audit-ready narrative summary that a
# compliance officer or senior manager can read, sign off on,
# and file as a formal record.
#
# In a real RBC workflow this summary would be:
# 1. Attached to the loan application file
# 2. Reviewed by a senior compliance officer
# 3. Stored in the document management system
# 4. Referenced in regulatory reporting
#
# The format mirrors how RBC's internal compliance memos
# are actually structured — executive summary first,
# findings with citations, then recommended actions.

SYSTEM_PROMPT = """You are a compliance officer assistant at a major 
Canadian bank regulated by OSFI. You generate formal audit-ready 
compliance summaries from financial document analysis.

STRICT RULES:
- Use formal compliance language appropriate for regulatory filing
- Every finding must cite a specific source and page number
- Never state conclusions not supported by the provided evidence
- Flag any gaps in the analysis explicitly
- Confidence level must reflect evidence quality
- Return ONLY valid JSON — no explanation, no markdown fences

Your summaries will be reviewed by senior compliance officers
and may be referenced in regulatory submissions to OSFI."""

SUMMARY_PROMPT = """Generate a formal compliance summary based on the 
following financial document analysis.

DOCUMENT: {document_name}
ANALYSIS DATE: {timestamp}
ANALYST: FinSight AI (Decision Support Only)

RETRIEVED EVIDENCE:
{context}

RISK INDICATORS ALREADY EXTRACTED:
{risk_summary}

Generate this exact JSON structure:
{{
  "compliance_summary": {{
    "document_name": "{document_name}",
    "summary_date": "{timestamp}",
    "prepared_by": "FinSight AI — Decision Support Only",
    "review_required": true,
    "executive_summary": "2-3 sentence high level overview for senior management",
    "overall_assessment": "PASS / REQUIRES_REVIEW / ESCALATE",
    "confidence_level": "HIGH / MEDIUM / LOW",
    "confidence_rationale": "why this confidence level was assigned",
    "key_findings": [
      {{
        "finding_id": "F001",
        "category": "risk category",
        "severity": "HIGH / MEDIUM / LOW / INFORMATIONAL",
        "finding": "specific finding quoted or paraphrased from document",
        "source": "document name",
        "page": 0,
        "implication": "what this means for the institution",
        "action_required": "YES / NO / MONITOR"
      }}
    ],
    "compliance_checklist": {{
      "capital_adequacy_mentioned": true,
      "liquidity_ratios_mentioned": true,
      "stress_testing_mentioned": true,
      "risk_appetite_mentioned": true,
      "audit_trail_present": true
    }},
    "gaps_identified": [
      "any area where evidence was insufficient"
    ],
    "recommended_actions": [
      {{
        "priority": "HIGH / MEDIUM / LOW",
        "action": "specific action to take",
        "timeline": "immediate / 30 days / 90 days / ongoing"
      }}
    ],
    "disclaimer": "This summary is generated by AI for decision support only. It does not constitute a formal compliance opinion. Review by a qualified compliance officer is required before any regulatory filing or credit decision."
  }}
}}

Generate the compliance summary now:"""


def run_compliance_summariser(
    context:       str,
    document_name: str,
    risk_data:     dict,
    chunks:        list
) -> dict:
    """
    Generates a formal audit-ready compliance summary.

    Takes as input:
    - context: formatted retrieved chunks from retrieval agent
    - document_name: source PDF filename
    - risk_data: structured output from risk extractor
    - chunks: raw chunk list for metadata

    Returns structured compliance summary with:
    - Executive summary for senior management
    - Key findings with citations
    - Compliance checklist
    - Gaps identified
    - Recommended actions with priorities and timelines

    Why structure the output this way?
    RBC's compliance memos follow a standard format —
    executive summary, findings, checklist, actions.
    Mirroring this format means the output slots directly
    into existing workflows without reformatting.
    """
    start_time = time.time()
    timestamp  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    llm = ChatOpenAI(
        model=LLM_MODEL,
        temperature=0,
        openai_api_key=os.getenv("OPENAI_API_KEY")
    )

    # Format risk summary for the prompt
    risk_summary = json.dumps(risk_data, indent=2) if risk_data else "No risk data available"

    prompt = SUMMARY_PROMPT.format(
        document_name=document_name,
        timestamp=timestamp,
        context=context[:3000],  # cap context to avoid token limits
        risk_summary=risk_summary[:1000]
    )

    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt)
    ]

    try:
        response     = llm.invoke(messages)
        raw_response = response.content.strip()

        # Clean markdown fences if present
        if raw_response.startswith("```"):
            raw_response = raw_response.split("```")[1]
            if raw_response.startswith("json"):
                raw_response = raw_response[4:]

        summary_data = json.loads(raw_response)
        latency_ms   = round((time.time() - start_time) * 1000, 1)

        return {
            "success":      True,
            "summary":      summary_data.get("compliance_summary", summary_data),
            "latency_ms":   latency_ms,
            "error":        None
        }

    except json.JSONDecodeError as e:
        return {
            "success":    False,
            "summary":    None,
            "latency_ms": round((time.time() - start_time) * 1000, 1),
            "error":      f"JSON parse error: {e}"
        }
    except Exception as e:
        return {
            "success":    False,
            "summary":    None,
            "latency_ms": round((time.time() - start_time) * 1000, 1),
            "error":      str(e)
        }


def format_compliance_report(summary: dict) -> str:
    """
    Formats the compliance summary into a readable report
    for display in the Streamlit UI.

    This is what the compliance officer actually reads —
    clean, structured, formal language with clear findings
    and actions.
    """
    if not summary:
        return "Compliance summary not available."

    lines = [
        "=" * 65,
        "FINSIGHT COMPLIANCE SUMMARY",
        "=" * 65,
        f"Document:    {summary.get('document_name', 'N/A')}",
        f"Date:        {summary.get('summary_date', 'N/A')}",
        f"Prepared by: {summary.get('prepared_by', 'N/A')}",
        f"Assessment:  {summary.get('overall_assessment', 'N/A')}",
        f"Confidence:  {summary.get('confidence_level', 'N/A')}",
        "",
        "EXECUTIVE SUMMARY:",
        summary.get('executive_summary', 'N/A'),
        "",
        "KEY FINDINGS:"
    ]

    for finding in summary.get("key_findings", []):
        lines.extend([
            f"\n  [{finding.get('finding_id', 'F?')}] "
            f"{finding.get('category', '').upper()} — "
            f"Severity: {finding.get('severity', 'N/A')}",
            f"  Finding:    {finding.get('finding', 'N/A')[:120]}...",
            f"  Source:     {finding.get('source', 'N/A')}, "
            f"page {finding.get('page', 0)}",
            f"  Implication: {finding.get('implication', 'N/A')[:100]}...",
            f"  Action:     {finding.get('action_required', 'N/A')}"
        ])

    lines.append("\nRECOMMENDED ACTIONS:")
    for action in summary.get("recommended_actions", []):
        lines.append(
            f"  [{action.get('priority', 'N/A')}] "
            f"{action.get('action', 'N/A')} "
            f"({action.get('timeline', 'N/A')})"
        )

    gaps = summary.get("gaps_identified", [])
    if gaps:
        lines.append("\nGAPS IDENTIFIED:")
        for gap in gaps:
            lines.append(f"  - {gap}")

    lines.extend([
        "",
        "=" * 65,
        "DISCLAIMER:",
        summary.get("disclaimer", "Review required before any regulatory filing."),
        "=" * 65
    ])

    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent.parent))

    from agents.retrieval import get_vectorstore, run_retrieval_agent
    from agents.risk_extractor import run_risk_extractor

    print("Testing compliance summariser...")
    print("Loading vectorstore...")

    vectorstore = get_vectorstore()

    query  = "risk factors credit market liquidity regulatory compliance capital"
    result = run_retrieval_agent(query, vectorstore)

    print(f"Retrieved {len(result['chunks'])} chunks")
    print("Running risk extraction...")

    risk_result = run_risk_extractor(
        context       = result["context"],
        document_name = result["sources"][0] if result["sources"] else "unknown",
        chunks        = result["chunks"]
    )

    print("Running compliance summariser...\n")

    summary_result = run_compliance_summariser(
        context       = result["context"],
        document_name = result["sources"][0] if result["sources"] else "unknown",
        risk_data     = risk_result.get("risk_data", {}),
        chunks        = result["chunks"]
    )

    if summary_result["success"]:
        print(f"SUCCESS — Latency: {summary_result['latency_ms']}ms\n")
        print(format_compliance_report(summary_result["summary"]))
        print("\nFull JSON:")
        print(json.dumps(summary_result["summary"], indent=2))
    else:
        print(f"FAILED: {summary_result['error']}")